# top level stuff you probably don't need to touch
highlighter: pygments
markdown: rdiscount
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://blog.zaiyiqi.xyz/
basurl: /
title: 壮士
author: 壮士
description: Personal blog and resume
avatar: fabio.png
email: xiahao90@fexmail.com
github: xiahao90
twitter: xiahao90
google_analytics: UA-47728743-1